$(document).ready(function(){
   $("#stat1").draggable();
   $("#stat2").draggable();
   $("#stat3").draggable();
   $("#stat4").draggable();
   $("#stat5").draggable();
   $("#stat6").draggable();
   $("#strCon").droppable();
   $("#dexCon").droppable();
   $("#conCon").droppable();
   $("#intCon").droppable();
   $("#wisCon").droppable();
   $("#chaCon").droppable();
});